### ISSUE TITLE
Data::Table::Text

### ISSUE THREAD

**Issue by philiprbrenan** [ronsavage/Text-Table-Manifold#3]
Hi **Ron**:

Please could you add:

https://metacpan.org/pod/Data::Table::Text

to the **See Also** section of: 

https://metacpan.org/pod/Text::Table::Manifold

Much appreciated.

**Phil**

**Comment by ronsavage** [comment]
I've done that, but I don't think it's worth releasing a new version.
Thanx.

**Comment by philiprbrenan** [comment]
Much appreciated!
